sudo: required
language: go
go:
  - 1.6
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential pkg-config libxinerama-dev libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libbullet-dev libassimp-dev
script:
  - go get -v -t ./...
  - go get -u github.com/golang/lint/golint
  - golint ./...
  - test -z "$(golint ./...)"
  - GORACE="halt_on_error=1" go test -race -v ./...
  - go install -v ./...
