language: go
go:
  - 1.5
  - tip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential pkg-config libxinerama-dev libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libbullet-dev libassimp-dev
install:
  - go get -t ./...
script:
  - golint ./...
  - test -z "$(golint ./...)"
  - GORACE="halt_on_error=1" go test -race -v ./...
