language: go
sudo: required
dist: trusty
go:
  - 1.5
  - tip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install build-essential pkg-config libxinerama-dev libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libbullet-dev libassimp-dev
script:
  - go get -t ./...
  - golint ./...
  - test -z "$(golint ./...)"
  - GORACE="halt_on_error=1" go test -race -v ./...
